import '@testing-library/jest-dom/vitest'

// Mock window.electronAPI for store tests that reference it
Object.defineProperty(window, 'electronAPI', {
  value: {
    saveFavorites: vi.fn(),
    loadFavorites: vi.fn(),
    readDir: vi.fn(),
    readFile: vi.fn(),
    readFileBinary: vi.fn(),
    writeFile: vi.fn(),
    rename: vi.fn(),
    mkdir: vi.fn(),
    delete: vi.fn(),
    getHomeDir: vi.fn(),
    autocomplete: vi.fn(),
    gitBranch: vi.fn(),
    minimize: vi.fn(),
    maximize: vi.fn(),
    close: vi.fn(),
    isMaximized: vi.fn(),
    createTerminal: vi.fn(),
    writeTerminal: vi.fn(),
    resizeTerminal: vi.fn(),
    killTerminal: vi.fn(),
    onTerminalData: vi.fn(),
    onTerminalExit: vi.fn(),
    loadConfig: vi.fn().mockResolvedValue(null),
    saveConfig: vi.fn().mockResolvedValue(undefined),
    patchConfig: vi.fn().mockResolvedValue({}),
    loadCache: vi.fn().mockResolvedValue(null),
    saveCache: vi.fn().mockResolvedValue(undefined),
    invalidateCache: vi.fn().mockResolvedValue(undefined),
    createWorkSession: vi.fn().mockImplementation(async (s: any) => s),
    updateWorkSession: vi.fn().mockResolvedValue(null),
    getWorkSession: vi.fn().mockResolvedValue(null),
    getWorkSessionsByTicket: vi.fn().mockResolvedValue([]),
    getAllWorkSessions: vi.fn().mockResolvedValue([]),
    deleteWorkSession: vi.fn().mockResolvedValue(undefined),
    getTicketBinding: vi.fn().mockResolvedValue(null),
    setTicketBinding: vi.fn().mockResolvedValue(undefined),
    getAllTicketBindings: vi.fn().mockResolvedValue({}),
    removeTicketBinding: vi.fn().mockResolvedValue(undefined),
    loadRecentProjects: vi.fn().mockResolvedValue([]),
    saveRecentProjects: vi.fn().mockResolvedValue(undefined),
    listClaudeSessions: vi.fn().mockResolvedValue([]),
    setAutoPilot: vi.fn(),
    setTmuxOption: vi.fn(),
    capturePane: vi.fn().mockResolvedValue(null),
  },
  writable: true
})
